### ISSUE TITLE
[Feature Request] - Include filepath and name in the hash 

### ISSUE THREAD

**Issue by gpiccinni** [cakepietoast/checksumdir#16]
Hi it would be helpful to have an option to include filename and structure in the checksum.
Mostly because when renaming a file the current implementation does not take into account the renaming.

**Comment by gpiccinni** [comment]
Hi is there any update on this? 
Is there anything I can do to move this PR forward ?
Looking forward to your feedback.
G

**Comment by to-mc** [comment]
Thanks for the PR! Its included in 1.2.0 release.
