### ISSUE TITLE
Why ignore hidden files?

### ISSUE THREAD

**Issue by fladd** [cakepietoast/checksumdir#2]
It seems that checksumdir ignores hidden file (`.*`). Is there any reason for this? How would I hash my dotfile diretory?

**Comment by to-mc** [comment]
No good reason, it just matched the use case at the time. As of version 1.1.0, it will no longer ignore hidden files by default - you can revert to previous behaviour using --ignore-hidden.

**Comment by fladd** [comment]
Fantastic, thanks!
