### ISSUE TITLE
excluded_extensions is ignored if "--ignore-hidden" is False (the default)

### ISSUE THREAD

**Issue by idahogray** [cakepietoast/checksumdir#5]
excluded_extensions is not used when "--ignore-hidden" is False.

I verified this by getting the sha256 checksum on one of my Python libraries. I want to exclude the pyc files. However, I noticed the result changed every time I deleted one of the pyc files in the library.

I reviewed the code and it appears that this possibly got left out after the --ignore-hidden option was added.

**Comment by to-mc** [comment]
Fixed in version 1.1.4
