### ISSUE TITLE
Different Results on Mac vs PC

### ISSUE THREAD

**Issue by Mochnant** [cakepietoast/checksumdir#6]
I'm not sure why, but I have noticed the same file gets a different hash result when run on Mac vs PC.  I am transferring them using Dropbox, and not saving or otherwise editing them in between hashing.

I checked the checksumdir source and it is using 'rb' mode on open.  Could there be something else causing this?  Thanks!

**Comment by Mochnant** [comment]
Still noticing this issue, Mac vs Windows.  I've confirmed the files are identical, including line endings.

**Comment by baterflyrity** [comment]
Hi there. I've noticed that this happens due to arbitrary order of received from OS files and folders. So I've added their sorting and pushed to git. Maybe someone will need this small changes.

**Comment by Mochnant** [comment]
That's great news, @baterflyrity!  I'd love to see this fix/change get into the repo.  Is there a PR coming for this?  I didn't notice one yet.

**Comment by baterflyrity** [comment]
@Mochnant my bad - forgot to fork. Now it's all must be done. You can check and give a feedback.

**Comment by Mochnant** [comment]
Great, thanks, @baterflyrity!

**Comment by to-mc** [comment]
Fixed in 1.1.7
